insert into review values (13, 20, 'related', 'Highly related', "This paper presents research that focuses on high-level model formation, explanation, and metareasoning. The results model actual human subject data collected in the laboratory. The approach is from a strong cognitive systems perspective.");
insert into review values (13, 20, 'extension', 'Substantial extension', "Few people in AI or Cognitive Science examine the process of explanation. Thus this represents significant research that fills a gap in the field. However the authors do not seem to be aware of some of the other approaches to explanation that do exist and rather focus on their own work or cite very old machine learning approaches such as EBL that is tangential to their approach. See for example the following. 
Roth-Berghofer, T., & Richter, M. M. (Eds.) (2008). Special issue on explanation. Künstliche Intelligenz (Artificial Intelligence), 22(2). 
Roth-Berghofer, T., & Schultz, S. (Eds.) (2005). Explanation-aware computing: Papers from the AAAI Fall Symposium (Technical Report No. FS-05-04). Menlo Park, CA: AAAI Press.
Roth-Berghofer, T., Schultz, S., Bahls, D., & Leake, D. B. (Eds.) (2007). Explanation-aware computing: Papers from the 2007 AAAI Workshop (Technical Report No. WS-07-06). Menlo Park, CA: AAAI Press.
In the larger cognitive science context, the authors may want to examine the following source and relate their work to it. 
Keil, F. C., & Wilson, R. A. (Eds.) (2000). Explanation and cognition. Cambridge, MA: MIT Press.");   
insert into review values (13, 20, 'claims', 'Clear claims', "The claims are laid out well, and the introduction is a clear statement of their approach, claims, and results in an accessible and compelling manner.");
insert into review values (13, 20, 'convincing', 'Very convincing', "The authors present a detailed discussion of the technical methods, and they present simulation results that model explanation in human subjects. The implementation and the behavior modeled are non-trivial.");
insert into review values (13, 20, 'effective', 'Somewhat effective', "  The paper starts out very clear and accessible. However the technical detail is sometimes difficult to follow. Indeed the paper suffers from too much detail at times. For example Fig 4 does not seem to be as helpful as other figures, and the details related to this figure are not central. Indeed the paper could easily be split into two papers. At times the technical explanations obscure the bigger picture rather than shed light on it. 
  As an aside the term pre-order needs definition.");
insert into review values (13, 20, 'comment', '', "The authors do not motivate how this research represents a metareasoning approach as stated by the subtitle. They use the term metareasoning in the context of comparing and deciding between competing explanations. I suppose that this is reasoning about one’s own knowledge, and they do mention metaknowledge. But the system does not reason about its own reasoning process per se, so in a stricter sense it may not be metareasoning (or they should explain how it does reason about reasoning). In any case, the authors do not explain, and the reader should not have to infer the relationship. The authors also do not relate the research to other research on metareasoning or metacognition. See for example the following. 
Cox, M. T., & Raja, A. (Eds.) (2011). Metareasoning: Thinking about thinking. Cambridge, MA: MIT Press.
The formatting of this paper does not strictly follow the AAAI guidelines. The AAAI copyright is missing. The section headers should not be numbered. The references are not in the correct formatting style. Figure 2 should be a table rather than a figure. Figure 2 (or Table 2 if you make the conversion) should be inserted in the body after the first reference to it rather than before. 
In section 2.2, the authors use colon in items 1 and 3 but not in item 2. I actually find the colons to be superfluous and would leave them out. Colons are overused in much of this paper.
Given the organizational statements in the first paragraph of section 3, you might consider making subsections 3. 2 and 3.3 further subsections (i.e., 3.2.1 and 3.2.2 but dropping the numbering altogether). 
Footnotes should come after a period or comma in a sentence rather than before. 
It was unusual to see human subject names used in this paper. I assume that they are not their real names, but still this appears odd. 
You should insert your grant numbers in the acknowledgments section.");
insert into review values (13, 20, 'meeting', 'Accept as talk', "");
insert into review values (13, 20, 'journal', 'Accept paper', "");