drop table if exists country;

create table if not exists country (
  id integer primary key,
  name text
);

insert into country values (1, 'Afghanistan');
insert into country values (2, 'Albania');
insert into country values (3, 'Algeria');
insert into country values (4, 'American Samoa');
insert into country values (5, 'Andorra');
insert into country values (6, 'Angola');
insert into country values (7, 'Anguilla');
insert into country values (8, 'Antarctica');
insert into country values (9, 'Antigua and Barbuda');
insert into country values (10, 'Argentina');
insert into country values (11, 'Armenia');
insert into country values (12, 'Armenia');
insert into country values (13, 'Aruba');
insert into country values (14, 'Australia');
insert into country values (15, 'Austria');
insert into country values (16, 'Azerbaijan');
insert into country values (17, 'Azerbaijan');
insert into country values (18, 'Bahamas');
insert into country values (19, 'Bahrain');
insert into country values (20, 'Bangladesh');
insert into country values (21, 'Barbados');
insert into country values (22, 'Belarus');
insert into country values (23, 'Belgium');
insert into country values (24, 'Belize');
insert into country values (25, 'Benin');
insert into country values (26, 'Bermuda');
insert into country values (27, 'Bhutan');
insert into country values (28, 'Bolivia');
insert into country values (29, 'Bosnia and Herzegovina');
insert into country values (30, 'Botswana');
insert into country values (31, 'Bouvet Island');
insert into country values (32, 'Brazil');
insert into country values (33, 'British Indian Ocean Territory');
insert into country values (34, 'Brunei Darussalam');
insert into country values (35, 'Bulgaria');
insert into country values (36, 'Burkina Faso');
insert into country values (37, 'Burundi');
insert into country values (38, 'Cambodia');
insert into country values (39, 'Cameroon');
insert into country values (40, 'Canada');
insert into country values (41, 'Cape Verde');
insert into country values (42, 'Cayman Islands');
insert into country values (43, 'Central African Republic');
insert into country values (44, 'Chad');
insert into country values (45, 'Chile');
insert into country values (46, 'China');
insert into country values (47, 'Christmas Island');
insert into country values (48, 'Cocos (Keeling) Islands');
insert into country values (49, 'Colombia');
insert into country values (50, 'Comoros');
insert into country values (51, 'Congo');
insert into country values (52, 'Congo, The Democratic Republic of The');
insert into country values (53, 'Cook Islands');
insert into country values (54, 'Costa Rica');
insert into country values (55, 'Cote D''ivoire');
insert into country values (56, 'Croatia');
insert into country values (57, 'Cuba');
insert into country values (58, 'Cyprus');
insert into country values (59, 'Cyprus');
insert into country values (60, 'Czech Republic');
insert into country values (61, 'Denmark');
insert into country values (62, 'Djibouti');
insert into country values (63, 'Dominica');
insert into country values (64, 'Dominican Republic');
insert into country values (65, 'Easter Island');
insert into country values (66, 'Ecuador');
insert into country values (67, 'Egypt');
insert into country values (68, 'El Salvador');
insert into country values (69, 'Equatorial Guinea');
insert into country values (70, 'Eritrea');
insert into country values (71, 'Estonia');
insert into country values (72, 'Ethiopia');
insert into country values (73, 'Falkland Islands (Malvinas)');
insert into country values (74, 'Faroe Islands');
insert into country values (75, 'Fiji');
insert into country values (76, 'Finland');
insert into country values (77, 'France');
insert into country values (78, 'French Guiana');
insert into country values (79, 'French Polynesia');
insert into country values (80, 'French Southern Territories');
insert into country values (81, 'Gabon');
insert into country values (82, 'Gambia');
insert into country values (83, 'Georgia');
insert into country values (84, 'Georgia');
insert into country values (85, 'Germany');
insert into country values (86, 'Ghana');
insert into country values (87, 'Gibraltar');
insert into country values (88, 'Greece');
insert into country values (89, 'Greenland');
insert into country values (90, 'Greenland');
insert into country values (91, 'Grenada');
insert into country values (92, 'Guadeloupe');
insert into country values (93, 'Guam');
insert into country values (94, 'Guatemala');
insert into country values (95, 'Guinea');
insert into country values (96, 'Guinea-bissau');
insert into country values (97, 'Guyana');
insert into country values (98, 'Haiti');
insert into country values (99, 'Heard Island and Mcdonald Islands');
insert into country values (100, 'Honduras');
insert into country values (101, 'Hong Kong');
insert into country values (102, 'Hungary');
insert into country values (103, 'Iceland');
insert into country values (104, 'India');
insert into country values (105, 'Indonesia');
insert into country values (106, 'Indonesia');
insert into country values (107, 'Iran');
insert into country values (108, 'Iraq');
insert into country values (109, 'Ireland');
insert into country values (110, 'Israel');
insert into country values (111, 'Italy');
insert into country values (112, 'Jamaica');
insert into country values (113, 'Japan');
insert into country values (114, 'Jordan');
insert into country values (115, 'Kazakhstan');
insert into country values (116, 'Kazakhstan');
insert into country values (117, 'Kenya');
insert into country values (118, 'Kiribati');
insert into country values (119, 'Korea, North');
insert into country values (120, 'Korea, South');
insert into country values (121, 'Kosovo');
insert into country values (122, 'Kuwait');
Insert into country values (123, 'Kyrgyzstan');
insert into country values (124, 'Laos');
insert into country values (125, 'Latvia');
insert into country values (126, 'Lebanon');
insert into country values (127, 'Lesotho');
insert into country values (128, 'Liberia');
insert into country values (129, 'Libyan Arab Jamahiriya');
insert into country values (130, 'Liechtenstein');
insert into country values (131, 'Lithuania');
insert into country values (132, 'Luxembourg');
insert into country values (133, 'Macau');
insert into country values (134, 'Macedonia');
insert into country values (135, 'Madagascar');
insert into country values (136, 'Malawi');
insert into country values (137, 'Malaysia');
insert into country values (138, 'Maldives');
insert into country values (139, 'Mali');
insert into country values (140, 'Malta');
insert into country values (141, 'Marshall Islands');
insert into country values (142, 'Martinique');
insert into country values (143, 'Mauritania');
insert into country values (144, 'Mauritius');
insert into country values (145, 'Mayotte');
insert into country values (146, 'Mexico');
insert into country values (147, 'Micronesia, Federated States of');
insert into country values (148, 'Moldova, Republic of');
insert into country values (149, 'Monaco');
insert into country values (150, 'Mongolia');
insert into country values (151, 'Montenegro');
insert into country values (152, 'Montserrat');
insert into country values (153, 'Morocco');
insert into country values (154, 'Mozambique');
insert into country values (155, 'Myanmar');
insert into country values (156, 'Namibia');
insert into country values (157, 'Nauru');
insert into country values (158, 'Nepal');
insert into country values (159, 'Netherlands');
insert into country values (160, 'Netherlands Antilles');
insert into country values (161, 'New Caledonia');
insert into country values (162, 'New Zealand');
insert into country values (163, 'Nicaragua');
insert into country values (164, 'Niger');
insert into country values (165, 'Nigeria');
insert into country values (166, 'Niue');
insert into country values (167, 'Norfolk Island');
insert into country values (168, 'Northern Mariana Islands');
insert into country values (169, 'Norway');
insert into country values (170, 'Oman');
insert into country values (171, 'Pakistan');
insert into country values (172, 'Palau');
insert into country values (173, 'Palestinian Territory');
insert into country values (174, 'Panama');
insert into country values (175, 'Papua New Guinea');
insert into country values (176, 'Paraguay');
insert into country values (177, 'Peru');
insert into country values (178, 'Philippines');
insert into country values (179, 'Pitcairn');
insert into country values (180, 'Poland');
insert into country values (181, 'Portugal');
insert into country values (182, 'Puerto Rico');
insert into country values (183, 'Qatar');
insert into country values (184, 'Reunion');
insert into country values (185, 'Romania');
insert into country values (186, 'Russia');
insert into country values (187, 'Russia');
insert into country values (188, 'Rwanda');
insert into country values (189, 'Saint Helena');
insert into country values (190, 'Saint Kitts and Nevis');
insert into country values (191, 'Saint Lucia');
insert into country values (192, 'Saint Pierre and Miquelon');
insert into country values (193, 'Saint Vincent and The Grenadines');
insert into country values (194, 'Samoa');
insert into country values (195, 'San Marino');
insert into country values (196, 'Sao Tome and Principe');
insert into country values (197, 'Saudi Arabia');
insert into country values (198, 'Senegal');
insert into country values (199, 'Serbia and Montenegro');
insert into country values (200, 'Seychelles');
insert into country values (201, 'Sierra Leone');
insert into country values (202, 'Singapore');
insert into country values (203, 'Slovakia');
insert into country values (204, 'Slovenia');
insert into country values (205, 'Solomon Islands');
insert into country values (206, 'Somalia');
insert into country values (207, 'South Africa');
insert into country values (208, 'South Georgia and The South Sandwich Islands');
insert into country values (209, 'Spain');
insert into country values (210, 'Sri Lanka');
insert into country values (211, 'Sudan');
insert into country values (212, 'Suriname');
insert into country values (213, 'Svalbard and Jan Mayen');
insert into country values (214, 'Swaziland');
insert into country values (215, 'Sweden');
insert into country values (216, 'Switzerland');
insert into country values (217, 'Syria');
insert into country values (218, 'Taiwan');
insert into country values (219, 'Tajikistan');
insert into country values (220, 'Tanzania, United Republic of');
insert into country values (221, 'Thailand');
insert into country values (222, 'Timor-leste');
insert into country values (223, 'Togo');
insert into country values (224, 'Tokelau');
insert into country values (225, 'Tonga');
insert into country values (226, 'Trinidad and Tobago');
insert into country values (227, 'Tunisia');
insert into country values (228, 'Turkey');
insert into country values (229, 'Turkey');
insert into country values (230, 'Turkmenistan');
insert into country values (231, 'Turks and Caicos Islands');
insert into country values (232, 'Tuvalu');
insert into country values (233, 'Uganda');
insert into country values (234, 'Ukraine');
insert into country values (235, 'United Arab Emirates');
insert into country values (236, 'United Kingdom');
insert into country values (237, 'United States');
insert into country values (238, 'United States Minor Outlying Islands');
insert into country values (239, 'Uruguay');
insert into country values (240, 'Uzbekistan');
insert into country values (241, 'Vanuatu');
insert into country values (242, 'Vatican City');
insert into country values (243, 'Venezuela');
insert into country values (244, 'Vietnam');
insert into country values (245, 'Virgin Islands, British');
insert into country values (246, 'Virgin Islands, U.S.');
insert into country values (247, 'Wallis and Futuna');
insert into country values (248, 'Western Sahara');
insert into country values (249, 'Yemen');
insert into country values (250, 'Yemen');
insert into country values (251, 'Zambia');
insert into country values (252, 'Zimbabwe');