insert into state values (NULL, 'Alabama', 'AL');
insert into state values (NULL, 'Alaska', 'AK');
insert into state values (NULL, 'Arizona', 'AZ');
insert into state values (NULL, 'Arkansas', 'AR');
insert into state values (NULL, 'California', 'CA');
insert into state values (NULL, 'Colorado', 'CO');
insert into state values (NULL, 'Connecticut', 'CT');
insert into state values (NULL, 'Delaware', 'DE');
insert into state values (NULL, 'District of Columbia', 'DC');
insert into state values (NULL, 'Florida', 'FL');
insert into state values (NULL, 'Georgia', 'GA');
insert into state values (NULL, 'Hawaii', 'HI');
insert into state values (NULL, 'Idaho', 'ID');
insert into state values (NULL, 'Illinois', 'IL');
insert into state values (NULL, 'Indiana', 'IN');
insert into state values (NULL, 'Iowa', 'IA');
insert into state values (NULL, 'Kansas', 'KS');
insert into state values (NULL, 'Kentucky', 'KY');
insert into state values (NULL, 'Louisiana', 'LA');
insert into state values (NULL, 'Maine', 'ME');
insert into state values (NULL, 'Maryland', 'MD');
insert into state values (NULL, 'Massachusetts', 'MA');
insert into state values (NULL, 'Michigan', 'MI');
insert into state values (NULL, 'Minnesota', 'MN');
insert into state values (NULL, 'Mississippi', 'MS');
insert into state values (NULL, 'Missouri', 'MO');
insert into state values (NULL, 'Montana', 'MT');
insert into state values (NULL, 'Nebraska', 'NE');
insert into state values (NULL, 'Nevada', 'NV');
insert into state values (NULL, 'New Hampshire', 'NH');
insert into state values (NULL, 'New Jersey', 'NJ');
insert into state values (NULL, 'New Mexico', 'NM');
insert into state values (NULL, 'New York', 'NY');
insert into state values (NULL, 'North Carolina', 'NC');
insert into state values (NULL, 'North Dakota', 'ND');
insert into state values (NULL, 'Ohio', 'OH');
insert into state values (NULL, 'Oklahoma', 'OK');
insert into state values (NULL, 'Oregon', 'OR');
insert into state values (NULL, 'Pennsylvania', 'PA');
insert into state values (NULL, 'Rhode Island', 'RI');
insert into state values (NULL, 'South Carolina', 'SC');
insert into state values (NULL, 'South Dakota', 'SD');
insert into state values (NULL, 'Tennessee', 'TN');
insert into state values (NULL, 'Texas', 'TX');
insert into state values (NULL, 'Utah', 'UT');
insert into state values (NULL, 'Vermont', 'VT');
insert into state values (NULL, 'Virginia', 'VA');
insert into state values (NULL, 'Washington', 'WA');
insert into state values (NULL, 'West Virginia', 'WV');
insert into state values (NULL, 'Wisconsin', 'WI');
insert into state values (NULL, 'Wyoming', 'WY');